version: '3'
services:
  rest-api:
    image: rest-api:1.0.0
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/books"]
      interval: 10s
      timeout: 5s
      retries: 5
    build: .